language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - sudo pip install .
    - sudo pip install flake8


script:

    - flake8 .
    # command to run tests
    - echo "No tests for now! Hooray!"